// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var firstVideo, secondVideo, video, videoContainer, _i, _len, _ref;
    videoContainer = $(".videoContainer");
    firstVideo = $("#first");
    secondVideo = $("#second");
    _ref = [firstVideo, secondVideo];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      video = _ref[_i];
      video.attr("height", videoContainer.height());
      video.attr("width", videoContainer.width());
    }
    firstVideo.on("ended", function() {
      return $("#first").hide('slow', function() {
        return $("#intermediate").show('slow', function() {
          return setTimeout(function() {
            return $("#intermediate").hide('slow', function() {
              return secondVideo.show('slow', function() {
                return this.play();
              });
            });
          }, 10000);
        });
      });
    });
    $("#start").click(function() {
      return firstVideo.show('slow', function() {
        return this.play();
      });
    });
    $.ajax("index.jade").then(function(data) {
      return $("#jade code").text(data);
    });
    $.ajax("eyemaginations.styl").then(function(data) {
      return $("#stylus code").text(data);
    });
    return $.ajax("eyemaginations.coffee").then(function(data) {
      return $("#coffee code").text(data);
    });
  });

}).call(this);
